### ISSUE TITLE
Some latters are covered and can not be selected

### ISSUE THREAD

**Issue by abdiG** [anini/sa7abah#2]
![covered latters](https://user-images.githubusercontent.com/46496734/55640938-a701bd80-579a-11e9-841e-975f6dc98d25.PNG)

I can across this bug when i was playing. i can take a look and see if i can figure it out.

**Comment by anini** [comment]
Hi @abdiG 
I see you are using Google Chrome translation functionality, this game can only be played with the Arabic letters and the Arabic interface :)
